app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: ${PROTOCOL}://${HOSTNAME}
backend:
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    upgrade-insecure-requests: false
    img-src: ["'self'", "https://itsyndicate.org", "https://gitlab.com", "https://secure.gravatar.com"]
  listen: ':7007'
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: ${PROTOCOL}://${HOSTNAME}
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  cors:
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
    origin: ${PROTOCOL}://${HOSTNAME}
  # config options: https://node-postgres.com/apis/client
  database:
    client: better-sqlite3
    connection: ':memory:'
  reading:
    allow:
      - host: ${GITLAB_HOSTNAME}
gitlab:
  allowedKinds:
    - Component
    - Resource
auth:
  environment: production
  providers:
    guest:
      userEntityRef: user:default/guest
      dangerouslyAllowOutsideDevelopment: true
    gitlab:
      production:
        clientId: ${AUTH_GITLAB_CLIENT_ID}
        clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
        audience: https://${GITLAB_HOSTNAME}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail
scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options
  defaultAuthor:
    name: ITSyndicate
    email: itsyndicate@gmail.com

catalog:
  providers:
    backstage:
      enabled: false
      schedule:
        frequency: { hours: 12 }
        timeout: { minutes: 30 }
