services:
  backstage:
    env_file: ".env"
    image: backstage:latest
    ports:
      - "7007:7007"
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      AUTH_GITLAB_CLIENT_ID: "${AUTH_GITLAB_CLIENT_ID}"
      AUTH_GITLAB_CLIENT_SECRET: "${AUTH_GITLAB_CLIENT_SECRET}"
      GITLAB_HOSTNAME: "${GITLAB_HOST}"
      PROTOCOL: "${PROTOCOL}"
      HOSTNAME: "${HOSTNAME}"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/demoplatform.itsyndicate.org/fullchain.pem:/etc/letsencrypt/live/demoplatform.itsyndicate.org/fullchain.pem
      - /etc/letsencrypt/live/demoplatform.itsyndicate.org/privkey.pem:/etc/letsencrypt/live/demoplatform.itsyndicate.org/privkey.pem

    depends_on:
      - backstage

