---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [itsyndicate-platform,guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: [itsyndicate-platform]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: itsyndicate-platform
spec:
  type: team
  children: []
